### ISSUE TITLE
Possible use of Team Viewer for Remote Interviews

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#1]
Need a way to record audio (a must) and screen (not required, but ideal) during remote interviews - with minimal effort on the user's part. 
In this Team Viewer video ("Online Meetings") it shows how to start a presentation, and add a user. If following this example, it is easy for the user to also share their screen, this looks like the closest use case to our needs. Need to double check that we're clear on:
1) What user needs to do to access meeting
2) That user can take over presenting
3) That doing this is accessible

Note: We would only consider this option with a user that approved screen recording, and that was able to relatively quickly set up Team Viewer on their end. If this isn't possible in about 5 minutes or less, we'll use a different (no screen recording) option.

**Comment by samreid** [comment]
TeamViewer requires a license except for communication between "family and friends": 
https://www.teamviewer.com/en/credentials/free-for-personal-use/
https://www.teamviewer.com/en/help/213-How-exactly-is-private-use-defined

A few years ago we asked TeamViewer if a non-profit open source project could use TeamViewer for free.  They said "no" and directed us to the $849 business license, so we decided not to use TeamViewer.
https://www.teamviewer.com/en/pricing/

Alternatively, it may be possible to use HTML5 code to record the audio and video for the session, but it would take some investigation and development effort.  Audio may be recorded like this:
https://www.html5rocks.com/en/tutorials/getusermedia/intro/
We may be able to record video through phet-io events, scenery snapshots, or foreignObjectRasterization.

**Comment by emily-phet** [comment]
@samreid - good to know. This issue was to keep track of conversation Taliesin and I just had in a meeting, and I forgot to mention she was also going to look into the licensing. I had thought there was a version that could be used for free by non-profits (from a long time ago), but I either misremembered or it has changed. 

Could you give a rough estimate of how many hours (or range of hours) it might take to support some type of recording that captures the visual aspects of the sim only (no audio)? You could imagine Balloons and Static Electricity as an example if it's sim specific.

In the long term, it would be ideal to be able to record the sim with HTML5 code - making it easy for the user and constraining recording to only the behavior we have interest in (the sim). Audio recording may not be needed, since we need to record the user speaking as well as any screen reader output anyway.

**Comment by samreid** [comment]
> Could you give a rough estimate of how many hours (or range of hours) it might take to support some type of recording that captures the visual aspects of the sim only (no audio)?

We have been developing this feature in PhET-iO and already used it in a few studies.  We record the input events and store them at Metacog, then use them to drive a playback of the simulation.  There are a few unknowns and caveats, see https://github.com/phetsims/phet-io/issues/553#issuecomment-243181171, but so far it has been working nicely.  @kathy-phet what do you think about repurposing that work for accessibility interviews?  Regarding the time estimates: it could take an hour or so to build a version that uses this strategy to record data, plus another hour to test it, 15 minutes to deal with password protection.

> Audio recording may not be needed, since we need to record the user speaking as well as any screen reader output anyway.

The html5rocks link I provided above shows how to record audio from the microphone (not just audio produced by the simulation), so it should be able to record the user speaking and the screen reader output as well.  I haven't experimented with this API before, but after some 3-5 hours of investigation we should have an idea of whether it would be "easy", "difficult", "impossible" and what platforms it may work on. @kathy-phet would be acceptable for us to record microphone audio and store it in Metacog?

**Comment by emily-phet** [comment]
@jessegreenberg - do you see any additional challenges coming up with having a version of accessible prototypes record input events? For example, issues with the type of input that is provided to the sim (e.g., from keyboard), or issues with maintaining a "research" version of the prototypes?

Otherwise, this would be wonderful for remote testing...and would possibly allow recording of some testing without the presence of a interviewer at all.

**Comment by kathy-phet** [comment]
Yes, I think we could use these both for research and store audio data. As long as irb says audio recording which I know it will.

Sent from my iPhone

On Nov 3, 2016, at 6:50 AM, emily-phet <notifications@github.com<mailto:notifications@github.com>> wrote:


@jessegreenberg<https://github.com/jessegreenberg> - do you see any additional challenges coming up with having a version of accessible prototypes record input events? For example, issues with the type of input that is provided to the sim (e.g., from keyboard), or issues with maintaining a "research" version of the prototypes?

Otherwise, this would be wonderful for remote testing...and would possibly allow recording of some testing without the presence of a interviewer at all.

-

**Comment by samreid** [comment]
> do you see any additional challenges coming up with having a version of accessible prototypes record input events? For example, issues with the type of input that is provided to the sim (e.g., from keyboard), or issues with maintaining a "research" version of the prototypes?

@jonathanolson and @jessegreenberg: I think scenery already records keyboard events.  But will we need to introduce additional "input event" recording for events that come directly from parallel DOM elements, from assistive technology?

**Comment by jonathanolson** [comment]
> But will we need to introduce additional "input event" recording for events that come directly from parallel DOM elements, from assistive technology?

Presumably, yes. @jessegreenberg correct me if I'm wrong.

**Comment by jessegreenberg** [comment]
Yes, that is my understanding.  We will want to add events like ```input``` ```change``` and ```click```.

**Comment by samreid** [comment]
> Yes, that is my understanding.  We will want to add events like ```input``` ```change``` and ```click```.

That seems like a good thing to investigate.  Another possibility in this case would be to add phet-io instrumentation for Balloons and Static Electricity, then use state recording and playbacks.  Instrumentation could take half a day, then it would take some more time to flesh out state playbacks and overlay the mouse position.

**Comment by terracoda** [comment]
@emily-phet, I am a little late to the this exciting conversation. TeamViewer is only free for personal use. My understanding from is that it is more accessible with screen readers than other conferencing and sharing systems, but I have very limited experience with it.

Looking forward to progress on issuer #2.

**Comment by kathy-phet** [comment]
@emily-phet - What about recording with Zoom? That way the interviewer could help the interviewee ensure they are not recording other information?

**Comment by samreid** [comment]
Upon investigation, #2 seems complicated and like it will require a long time to get it working.  +1 for investigating Zoom or alternatives.

**Comment by emily-phet** [comment]
@samreid and @kathy-phet - the use of video conference/screen sharing software is what we initially explored and tried to use. There does not exist an option that we can find that is easy to use with a screen reader and does not interfere with screen reader audio output. Zoom is not sufficiently accessible to support this - we have tried. In prior experience with screen reader users, Zoom is best accessed from a mobile device, and even then users had difficulty navigating the interface. In cases where the user could easily navigate the interface - e.g., Skype, the screen reader audio is decreased or muted when other audio is occurring (this supports the goal of having conversations with Skype, but not our goal of recording the screen reader output). Additional plug-ins are needed to alter this audio behavior. The use of Team Viewer with user testers was our last attempt at this, and licensing issues aside, that requires the user to download and open a file prior to use. 

The ideal would be to have some way to record what is occuring onscreen in the sim (bonus if we also know what keys were pressed), what is being output from the screen reader, and what the user is saying without requiring 1) any special knowledge from the user, 2) without having to walk a user through a series of steps, and 3) without requiring the user to navigate an application they are unfamiliar with. And the whole thing is platform independent, as we need to test with PC and Mac users.

**Comment by samreid** [comment]
According to https://zoom.us/accessibility

> Zoom is committed to ensuring universal access to our products and services, so that all meeting hosts and participants can have the best experience possible.

and

> Zoom services are now compatible with standard screen readers such as VoiceOver on iOS and OSX platforms, TalkBack on Android devices, and NVDA for Windows platforms. 

and 

> Zoom has made ongoing efforts to monitor and improve our accessibility features, and has resources dedicated to accessibility questions and concerns. To reach us, please email access@zoom.us or open a support ticket at support.zoom.us.

Is there something special we need to do to put Zoom in "accessibility mode"?  Has someone looked at the VPATs referred to in the above link?  Have we contacted Zoom to let them know the problem we are facing?

**Comment by emily-phet** [comment]
@samreid - can we have a quick discussion about this tomorrow? Unfortunately there is often a big difference in what is listed in a VPAT, what the application actually capable of, and what a user can figure out how to do...

**Comment by samreid** [comment]
> can we have a quick discussion about this tomorrow?

Sure, what time is best for you?

**Comment by samreid** [comment]
I also jotted down the breakdown of tasks in https://github.com/phetsims/a11y-research/issues/2#issuecomment-259046702

**Comment by emily-phet** [comment]
Not persuing use of TeamViwer any further. Related discussions are being held elsewhere.
