### ISSUE TITLE
Know what a11y features are enabled on a published sim

### ISSUE THREAD

**Issue by zepumph** [phetsims/a11y-research#103]
Currently there is no way to know what a11y features are enabled/supported in a phet sim on the published website, or locally. It would be nice for a variety of reasons.

* Good to be able to share examples on the website that adhere to specific set of a11y features, and to know what each sim's capabilities are without needing to run the sim.
* Important for binder, and the style guide.
* Adding it to the website metadata would be useful
* I believe that whatever implementation we go with here could be used to help "turn off" certain levels of a11y. This is useful if a common code component has more a11y (full interactive alerts) than the sim it's being used in. This may warrant its own issue eventually.

**Comment by zepumph** [comment]
Tagging @emily-phet because she brings this up a decent amount in terms of the style guide. Will you please assign a priority to this

**Comment by jessegreenberg** [comment]
We discussed this on 7/3/18 -  Moving forward, we should be careful to not paint ourselves into a corner when instrumenting common code components. This means that we don't want lots of "incomplete" dynamic alerts added to common code that would require substantial design or implementation time to make usable.

But ultimately, @emily-phet said that we don't want to spend time strictly defining "static" vs "dynamic" descriptions/alerts, and we don't need the ability to "turn off" certain a11y features when publishing a sim with "static descriptions".

For i18n, we won't want to make a sim translatable until it has full dynamic descriptions, so we won't need the distinction for rosetta.

@zepumph do you believe that this issue can  be closed for now?

**Comment by zepumph** [comment]
Sounds good, thanks for the nice summary!
