### ISSUE TITLE
Should simple sims have a Control Area?

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/a11y-research#118]
From https://github.com/phetsims/john-travoltage/issues/295, we would like to consider whether or not the "Control Area" in the PDOM is necessary in "simple" sims. So far, this has been sims like john-travoltage and friction where the only item in the control area is a Reset All button. But that might not be the only classification. Until this is discussed, we are going to include a "Control Area" in all of our a11y instrumented sims (from https://github.com/phetsims/john-travoltage/issues/295). But it is easy to remove them in the future if we need to.

@terracoda I am assigning this to you, but it sounds like this may not get work for some time as there is overlap with another paper/funding. Please feel free to remove your assignment until this becomes active if that is best.

**Comment by terracoda** [comment]
@jessegreenberg - thanks!

**Comment by terracoda** [comment]
@jessegreenberg, I think the Control Area is working well for simple sims. I am going to close this issue.
