### ISSUE TITLE
A11y View not working?

### ISSUE THREAD

**Issue by terracoda** [phetsims/a11y-research#126]
I just noticed that A11y Views are not working in BASE or Friction.
@jessegreenberg, is this a known issue?

<img width="1159" alt="screen shot 2018-11-20 at 1 32 22 pm" src="https://user-images.githubusercontent.com/1902116/48773960-28175700-ecc9-11e8-99c7-2b81631d63da.png">

<img width="1136" alt="screen shot 2018-11-20 at 1 33 27 pm" src="https://user-images.githubusercontent.com/1902116/48773969-2c437480-ecc9-11e8-98d8-44435eb0a815.png">

**Comment by jessegreenberg** [comment]
@terracoda said this happened on phettest after running pulling all.

**Comment by jessegreenberg** [comment]
I am able to see this after pulling all. Last change to the a11y-view was 4 months ago, must be something recent.

**Comment by jessegreenberg** [comment]
We arent receiving event messages from the sim anymore (which triggers initialization of the a11y view).

**Comment by jessegreenberg** [comment]
Seems to have come from changes in https://github.com/phetsims/tasks/issues/958

**Comment by jessegreenberg** [comment]
Thanks for reporting @terracoda, this was fixed in #958, and the a11y view is opening correctly in master again. Closing.
