### ISSUE TITLE
Teacher feedback survey

### ISSUE THREAD

**Issue by elharden2** [phetsims/a11y-research#135]
@emily-phet @terracoda @briannatomlinson @zepumph @jessegreenberg 
Here is the teacher feedback survey I created that I mentioned during the a11y retreat:   [bit.ly/phet-feedback](bit.ly/phet-feedback)

I'd love your feedback on it if you have time to go through it. As it is right now, I don't ask respondents to share their email addresses if they don't indicate they're either interested in receiving a11y-related emails from us or interested in working with us in some way.  

I'll be sharing this survey with teachers beginning next week at the 100kin10 summit (on Tues 3/26), so if you're able to give feedback before then, that'd be appreciated!  Thank you!

Also, is Taylor on GitHub?

**Comment by elharden2** [comment]
And if that link doesn't work, try [this one](https://cuboulder.qualtrics.com/jfe/form/SV_6zhbdewvt20Z1lj)

**Comment by jessegreenberg** [comment]
Thanks @elharden2. I don't have much expertise to provide feedback for such a thing. My only question is do we want any information about what assistive tech is being used in the classroom if applicable (Screen readers, Refreshable Braille displays, switch devices, 3D printers, others)? Maybe this is already part of Q4, or maybe it is a new question.

**Comment by jessegreenberg** [comment]
I just assigned folks above, all should feel free to remove assignment after review or if you don't have time to go through it before next week.

**Comment by elharden2** [comment]
Thanks @jessegreenberg!  I do believe this is the first GitHub issue I've created, so thanks all for your patience and assistance!

**Comment by twant** [comment]
@elharden2 I just filled out the survey and left some thoughts on the last question!

**Comment by elharden2** [comment]
Thanks @twant!  An no worries about feeling like you don't have proper expertise.  Even just feedback on question framing (is something confusing, could it be worded in a better way) is super helpful!

**Comment by zepumph** [comment]
There is an extra space before the parenthetical on Q7. 

I really like that selecting "none" deselects other options. 

Good work!

**Comment by briannatomlinson** [comment]
Ok! Some things I thought about while looking over your survey:

Q3: you've got a few statements related to I/DD -- do you want any other ones for vision impairment? (like difficulty distinguishing colors)

Q4: Are you interested in the distinction between something like one of the 2-in-1 laptops (the things that let you switch between tablet vs. laptop functionality)? I'm wondering b/c students might interact with them in different ways. <-- not sure what you're looking to find with this, mostly the distinction between 

Q5: does independent exploration mean one student only, or partner-based exploration? 

After Q6 if they use them often I'd actually ask them to provide which ones they use, if you're curious! 

@emily-phet would it be worth digging out the big list of questions we talked about with Prakriti back a year or so ago? I don't know if there's overlap/it's worth looking at again

**Comment by elharden2** [comment]
Thanks all, for your feedback!
