### ISSUE TITLE
A11y Sims Page - Mobile A11y icon?

### ISSUE THREAD

**Issue by terracoda** [phetsims/a11y-research#142]
We just published Ohm's Law with mobile A11y. Do we need an icon for that?

Tagging @emily-phet, @amanda-phet, @arouinfar, @oliver-phet.

**Comment by arouinfar** [comment]
@terracoda @emily-phet I suspect that mobile a11y features are different enough that it would merit its own icon. I'll add an item to the website meeting agenda. 

At minimum we should update the Ohm's Law listing on https://phet.colorado.edu/en/accessibility/prototypes

@terracoda and/or @emily-phet can you also confirm if that list is otherwise up-to-date?

**Comment by amanda-phet** [comment]
What are mobile a11y features?

**Comment by arouinfar** [comment]
> What are mobile a11y features?

I think that means pinch-to-zoom and compatible with mobile VoiceOver, but it would be good to confirm. @terracoda?

**Comment by emily-phet** [comment]
Thanks for asking! What we're referring to as "mobile a11y" in this case is: descriptions accessible from mobile devices. 
On non-mobile devices there is usually a physical keyboard or some other non-touch based option for navigating the screen reader. On mobile devices, screen readers use a different paradigm for input (so to speak). It takes additional development effort and approaches to ensure that the description is accessible via traditional (non-touch) input methods and also by mobile touch methods. @terracoda and @jessegreenberg to speak to this more eloquently, but that's the big picture idea.

Visual display features, such as pinch-to-zoom, are not included in what we're referring to here as 'mobile a11y', though that will progress further in the coming months.

**Comment by terracoda** [comment]
@emily-phet, you explain it correctly, in our original accessibility investigations, we explored keyboard accessibility only. The accessible interactions like the accessible content is off the actual screen, so our solution was not then also accessible on touch devices with a screen reader activated. 

"Mobile A11y" specifically means non-visual access on a mobile/touch device. Sims without "Mobile A11y" are already accessible on a mobile/touch device.

I consider "mobile a11y" in a similar category to alternative input, though in our case we have 2 distinct categories.

I'm wondering if we can just add a mobile phone icon to the keyboard icon when mobile a11y is present.

[keyboard icon]+[mobile phone icon]

Just an idea.

**Comment by amanda-phet** [comment]
I agree, a phone icons makes sense, and we will have that legend at the top
of the sims page to explain what it means.

**Comment by oliver-phet** [comment]
Here's a first pass at an icon for this:
![mobile_accessibility-icons](https://user-images.githubusercontent.com/5090275/60920247-fa315380-a254-11e9-8b57-23f0211545eb.gif)
Thoughts @emily-phet @terracoda ?

**Comment by emily-phet** [comment]
Nice! Maybe flip phone to be horizontal (tablet style), with the icon for dynamic descriptions in the middle? Then scaled down so the entire thing is the same size as the icons already on the accessibility page.

**Comment by terracoda** [comment]
Nice Oliver! And I like @emily-phet 's suggestions, too....sideways and dynamic descriptions icon.

**Comment by oliver-phet** [comment]
So, the images on the website are currently 100px wide by 116px tall, so a portrait orientation fit a little better. 
Here's a landscape view with a scaled-down dynamic description icon:
![accessibility-icons](https://user-images.githubusercontent.com/5090275/61065940-e8b98a00-a3c1-11e9-8299-844e49e370f0.gif)

Here's an example with a few icons in context. I think we initially went with the green icon color to differentiate it from the others:
![accessibility-page-test](https://user-images.githubusercontent.com/5090275/61066889-a2652a80-a3c3-11e9-81f4-a9d84a021f87.gif)

**Comment by amanda-phet** [comment]
We also didn't fill the bubble since we thought it could include either simple or dynamic descriptions.

**Comment by terracoda** [comment]
@amanda-phet, I like that idea. Fill the mobile a11y icon with the 1 of three icons:
- empty if no description, 
- plain lines if only simple description, 
- zig-zaggy lines if full description.

Nice idea!

**Comment by terracoda** [comment]
@amanda-phet, considering more recent comments in #898, we might not need the plain-lines icon for simple description.

**Comment by terracoda** [comment]
@amanda-phet,we might not need to do what was suggested https://github.com/phetsims/a11y-research/issues/142#issuecomment-510914109

**Comment by amanda-phet** [comment]
Since the icon has been designed and deployed, can this issue be closed?

**Comment by terracoda** [comment]
@amanda-phet shared new icon designs in https://github.com/phetsims/website/issues/951#issuecomment-569821242

We'll continue discussing design as needed in the website repo.

Closing this issue.

**Comment by terracoda** [comment]
I'll add that doing https://github.com/phetsims/a11y-research/issues/142#issuecomment-510914109 might be a little too granular for the website needs. 

At some point all sims will have Zoom enabled fro touch devices, so we may not need to have an icon explicitly for that. And we no longer call out "Simple Description".
