### ISSUE TITLE
Magnification design questions

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/a11y-research#147]
There are a couple of design questions related to improved accessibility from magnification that we want to understand. We are not sure at this time if any work on these is necessary. We hope that user feedback and interviews will inform if any of these are necessary. Listing out questions here:

- Should the sim pan with the dragged object with keyboard dragging like it does with mouse dragging?
  - Behavior would match mouse. But it is really nice to be able to drag something out of view with a keyboard and watch behavior that is in current view

- Should we make it possible to pan the sim with a keyboard while focus is on an object that uses arrow keys? Perhaps a hotkey, maybe pressing "escape" makes focus go away so you can continue to pan.

- Is the "pan to focus" too aggressive?
  - When focus moves, we pan so the focused node moves to the center of the screen. This creates a lot of movement, maybe it is too much.

- Do we want to add the "Anchor mode"/"Smart Panning" option?
  - By default, the sim pans to follow keyboard focus.  We could add an option that disables this. This way keyboard focus can move around the sim doesn't pan and so you can observe changes without panning back and forth between controls.

- In interviews we should ask people what kinds of keyboard shortcuts the use if any (@terracoda added)

Assigning to @terracoda and @emily-phet for now and we can reconsider after we get a bit of user feedback.

**Comment by terracoda** [comment]
I am closing this issue until we need to work on Pan & Zoom.
