### ISSUE TITLE
Arrange for an introduction to making tweaks to description strings

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#155]
@Matthew-Moore240 
This is in response to conversation that came up in today's Molarity postmortem. 
I thought it would be useful for you to learn the process of tweaking a description string directly. The idea is not that you would necessarily do a lot of this, but that you would have this "tool in your toolbox" so to speak to use at times it seems beneficial, and learning how to do it might introduce you to more of how the code works that could provide other benefits. 

What I have in mind with this issue is that sometime (ideally this Quarter) you arrange a time with someone (perhaps @jessegreenberg) that works well for both of you, and that person shows you how to edit a text string, and you try it out yourself. I suggest recording the discussion (or at least, a portion at the end where you go through the steps) so you have it (and others, too!) available in case it's awhile before using this skill comes up in design.

**Comment by jessegreenberg** [comment]
@Matthew-Moore240 and I met today to go through this, we went through the steps to edit strings through the github UI, and committed changes as shown in the above two commits. Closing!
