### ISSUE TITLE
Can we set up a time for @zepumph to pair with @jessegreenberg

### ISSUE THREAD

**Issue by zepumph** [phetsims/a11y-research#17]
@kathy-phet and @emily-phet and @zepumph are going to meet at the end of the month to talk more about long term employment, and I think it would be good for this to happen before our meeting so I have a better idea about what to expect from accessibility. @jessegreenberg when would be good? I was thinking sometime next week. Tuesday and Wednesday work well for me. Tagging @ariel-phet so he is in the know.

**Comment by jessegreenberg** [comment]
@zepumph sounds great!  Tuesday afternoon, or any time Wednesday would work for me.

**Comment by zepumph** [comment]
Let's give it a good session on Wednesday, start sometime in the morning and see how we do. How about 10?

**Comment by jessegreenberg** [comment]
Sounds good to me, see you then @zepumph.

**Comment by zepumph** [comment]
Hey that went great today! Thanks for showing me around the a11y side of life. Closing
