### ISSUE TITLE
Need latest dev versions for sims for prototypes page

### ISSUE THREAD

**Issue by terracoda** [phetsims/a11y-research#186]
I need the latest dev versions for a few sims, so I can provide access to versions with unpublished features, e.g., Pan & Zoom and interactive Highlights

- [x] Molecules and Light 
- [x] Ohm' Law
- [x] Resistance in a Wire
- [x] Molarity
- [x] Gravity Force Lab (regular)
- [x] Faraday's Law

Adding:
- [x] **Quadrilateral** to the list

**Comment by jessegreenberg** [comment]
I see issues in inverse-square-law-common and gravity-force-lab that block publication (some related to Voicing). Do these need to be fixed for this issue @terracoda?
https://github.com/phetsims/inverse-square-law-common/issues/87
https://github.com/phetsims/gravity-force-lab-basics/issues/324

There are a couple in john-travoltage too but they look less serious.

**Comment by terracoda** [comment]
Hmm, I didn't realize there could be blocking issues.
I guess we have to wait to get dev links for the prototypes page.

**Comment by jessegreenberg** [comment]
I resolved those two issues. I don't see any other issues that would block this.  Ill make the dev versions now.

**Comment by jessegreenberg** [comment]
- Molecules and Light: https://phet-dev.colorado.edu/html/molecules-and-light/1.6.0-dev.7/phet/molecules-and-light_en_phet.html

- Ohm' Law: 
- Resistance in a Wire: 
- Molarity: 
 - Gravity Force Lab (regular): 
 - Faraday's Law: 

- Quadrilateral: https://phet-dev.colorado.edu/html/quadrilateral/1.0.0-dev.76/phet/quadrilateral_en_phet.html

**Comment by jessegreenberg** [comment]
OK, links prepared above. I think common code is in good shape right now but I don't know if there are any regressions in the above list of links compared to what is already on the prototypes page.

Back to you @terracoda.

**Comment by terracoda** [comment]
Thanks @jessegreenberg. I will have a look/listen.

**Comment by terracoda** [comment]
It is nice to see the Preferences Menu and Interactive Highlights in all these sims. I will update the links for the Assigning to me to update links on Prototypes page.

**Comment by terracoda** [comment]
I added these to these 7 links to the live website's Accessible Prototypes page.

**Comment by terracoda** [comment]
I have updated the website with the above prototype links. Closing.
