### ISSUE TITLE
Review Video Bumper & Add Sound

### ISSUE THREAD

**Issue by terracoda** [phetsims/a11y-research#187]
Sarah has created a new video bumper.

Here's the final version to review:
[https://drive.google.com/file/d/1M1I9OK4I7VMM4gzm-fyiBieOPWSL67hi/view?usp=share_link](https://drive.google.com/file/d/1M1I9OK4I7VMM4gzm-fyiBieOPWSL67hi/view?usp=share_link)

Sarah needs @emily-phet to have a final look before @Ashton-Morris adds sound to it.

Assigning to @emily-phet to comment that it is good to add sound, and to assign the issue to @Ashton-Morris.

Related to issue #181

**Comment by emily-phet** [comment]
This looks beautiful! Two comments:
- The opening PhET logo (PhET / Interactive Simulations - large on the screen) looks a little funny. The "Simulations" text is the thinner font, and it looks a little pixelated on my computer. Does it look like that to others?
- It's very fast. With all the animations it feels a little too fast. So I think we either decrease some of the animations, or let it be a few seconds longer overall. (A little longer is fine with me, like 10 seconds total).

**Comment by terracoda** [comment]
I agree with @emily-phet, that it feels fast. 
Slowing down the airplane, allowing for time to read the text at a relatively normal rate:
- PhET Interactive Simulations
- Inclusive Features
- {{Feature Title}}

would push the intro to about 10 seconds. I like the suggestion of slowing things down.

**Comment by terracoda** [comment]
I think the slower bumper looks good in Voicing and Alt Input videos.

**Comment by terracoda** [comment]
Tagging @emily-phet in case you haven't reviewed the new bumper yet.

**Comment by Ashton-Morris** [comment]
I have an updated bumper, will be working on sound today.

**Comment by Ashton-Morris** [comment]
I worked on three SFX bumper examples which you can view and listen to below.

- [PhET Intro Bumper SFX Standard.mp4](https://drive.google.com/file/d/1udQpqjLtj9k36YP4dOk8qdDssS247L0m/view?usp=share_link)
- [PhET Intro Bumper SFX Minimal.mp4](https://drive.google.com/file/d/1Ol7AXFULdWgfxArGkvltODCRiT0vMCQG/view?usp=share_link)
- [PhET Intro Bumper SFX Magic Spells.mp4](https://drive.google.com/file/d/1LVY8rX-sofLKQfDEhwotu33gpHaSldii/view?usp=share_link) ;-)

**Comment by terracoda** [comment]
Nice work Ashton. I like them all. 

Sound is not my forte, so take my feedback with that in mind. 

Personally, I like the lightness of the minimal version the best. That preference might have to do with volume of the the sounds in all the bumpers.

There seems to be a little flutter sound on the airplane in the magic version one which I like. I would be curious to hear what others think about the swoosh sound on the airplane. The plane is flying pretty fast, but I feel like a bit of a lighter swoosh - something more paper-y; maybe with the flutter - could give air plane a lighter feel?

But honestly, I defer to others because my ear is not the best critic.

**Comment by terracoda** [comment]
@emily-phet, what do you think?

**Comment by terracoda** [comment]
Just adding:
And I like the sparkly magic sound, too. 
I am wondering how the bumpers would sound with the voice over, "PhET Interactive Simulations presents Inclusive Features"? Any chance of pairing the sound with the voice over?

**Comment by emily-phet** [comment]
Hmm, I'm not sure if this is intended to stand alone, or if it's intended to have music playing in the background as well. 

I've been imagining that there would be a musical riff that played for the intro, like other PhET videos, the also had a swooshing sound. So with that in mind, the minimal swooshing would probably make the most sense so there's not competition between the airplane sounds and the intro music. 

I agree with Taliesin that as it is in the links with only the airplane sound, it sounds a bit heavy. Not sure if it needs that heaviness to work with music playing as well. Maybe if there was a little bit of a rustling quality to it, like you would get with a relatively flimsy paper in the wind, would help give more of a "paper airplane" feel. 

@Ashton-Morris If you know of a way to get that kind of rusting quality without a lot of effort, go for it. If it's unclear or very effortful, let's just see how the current sound effects sound with music layered in. 

Additionally, I would love to try having the text on screen read out - no additional words. Just "PhET Interactive Simulations", "Inclusive Features" "Feature Name" as these appear on screen. @terracoda I think you were planning to record your own voice saying these things after last week's meeting, correct?

**Comment by terracoda** [comment]
SB shared a version the voice and I like the one that says presents, but they both work well.
I also like the one where the music starts with the start of the inclusive feature. That creates a nice transition after the swoosh, or maybe with the final swoosh.

**Comment by terracoda** [comment]
@emily-phet, there are now bumper versions with the music and voice overs.

Sarah asked me to try 
- "PhET Interactive Simulations presents Inclusive Features" + "Feature Name" as well as
- "PhET Interactive Simulations" + "Inclusive Features" + "Feature Name"

"INTRODUCTION_TO_Interactive_Description_v3" has music and voice over with "presents".
"Inclusive_Feature_Bumper_Full_Audio" has it without "presents".

And "Inclusive_Features_Bumper_no_music" has the music come in at the end.

I personally, like the music coming in at the end, but I am good with what others like.

**Comment by Ashton-Morris** [comment]
I can work on another version with a different paper rustle. The one I was using had a wax paper recording but I record or find one that has a different paper source.

**Comment by emily-phet** [comment]
Yup - I like the rustling!

**Comment by terracoda** [comment]
I think everyone reviewed this version. I can post another issue, or reopen this one once there is more to review.

**Comment by terracoda** [comment]
I think the bumper is complete, and we are just working on videos, so closing for now.
