### ISSUE TITLE
Editing a group photo for website

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#188]
As part of one of my projects, we took a series of group photo (~30 people). I need a few edits to the photo. @mariahmaephet can you help with this?

- finding the best photo from the set (re open eyes, expressions, etc.). 
- If none are suitable as is, editing a head or two from one into the best overall.
- if possible, adding in a missing person (from a separate photo taken in the same space).

**Comment by mariahmaephet** [comment]
Sure! If it can be done tomorrow--I'll be taking off for a trip Wednesday without my computer and won't be back until the 8th.

**Comment by emily-phet** [comment]
Here's a link to the photos: Some have me in it (sitting in the front row) others do not. The final (best) one should have me in it. 
I can't find the additional photo of the missing person...so let's just go with these. Please find the best one and if you can, address any issues in that one with open eyes / expressions. If I recall correctly, there was one individual in particular who was caught with an exaggerated expression in most of the them. If you could also remove the cushion that's in the lower left of photo that would be fantastic as well!
https://drive.google.com/drive/folders/1oCmVWqZWswAd_SRhFZxDwGMY3KaSGpbB?usp=share_link

**Comment by emily-phet** [comment]
Edited photo was delivered!
