### ISSUE TITLE
Determine best wording for the Reset All alert

### ISSUE THREAD

**Issue by terracoda** [phetsims/a11y-research#21]
In github issue https://github.com/phetsims/scenery-phet/issues/291, @jbphet had a concern about the wording of the _Reset All_ alert, and suggested we change it from:

- "Sim screen restarted. Everything reset." to
- "Simulation screen has been reset."

At the PhET/IDRC Meeting (March 14) there was some agreement that this was a good change, but upon closer review @emily-phet and @terracoda would prefer not to change it.

This issue is to clarify pros and cons of the two versions, and to determine the best wording for the Reset All alert.

**Comment by terracoda** [comment]
First, it is important to consider that the alert is read in the context of the reset button's label, and that the user actively decides to press the button after hearing the label, "Reset All."

**So in context Version 1 sounds like this:**
- "Reset All, button." (User presses the button) and then hears:
    - "Sim screen restarted. Everything reset."

What I like about this alert (alert credit: Ariel and Jesse) is that:
1. It succinctly contains redundancy that emphasizes what has happened. 
     - The screen has gone back to like it was in the beginning (on page load) and all the objects in the sim have been reset.
2. The phrase construction is very simple. 
    - Verbs are in the _simple past tense_ (versus the _present perfect_ in version 2).
    - And though there are 2 sentences, each one is very short. The second sentence could be easily skipped the next time the user hears the alert.
3. The emphasis on "Everything reset" differentiates the alert from other possible reset buttons in the sim (e.g. the Reset Balloon button in Balloons and Static Electricity).
4. Uses the simple noun "Sim" instead of "Simulation".

**Version 2 sounds like this:**
- "Reset All, button." (User presses the button) and then hears:
    - "Simulation screen has been reset."

What I like less about this alert is that:
1. It does not make the description significantly shorter or more clear. 
   - It is only one syllable shorter than version 1, and contains less information.
2. It still contains redundancy in that it repeats the label wording "reset", but it does not offer any further clarification of what reset means in terms of what just happened. 
3. Uses the more complex language: "Simulation" and "has been."

Any thoughts from others: @emily-phet, @jessegreenberg, @jhung, @jobara? Maybe @ariel-phet would like to chime in on this issue?  And sorry, I don't know the github handles for Caren and Ashley.

**Comment by emily-phet** [comment]
@jessegreenberg Unless there is significant concern over this, I think we should just go with Option 1 above. After discussing further with @terracoda and considering it further, I like how option 1 reads after the "reset all" button, and that the use of "reset" and "restarted" provides clarification if one of those two words is unclear.

**Comment by jessegreenberg** [comment]
Sounds good @emily-phet and @terracoda, we will change to option 1.

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet changed to option 1 in the above commit, closing this issue.

**Comment by carenwatkins** [comment]
@terracoda @jessegreenberg @emily-phet I know this issue has been closed but we wanted to note that perhaps we may have to revisit the language again when applying it to Sims with multiple screens. For example Skate Park and Forces & Motion that each have two reset layers: restart skater or return and reset screen. @jhung

**Comment by jessegreenberg** [comment]
Good point @carenwatkins, reopening this issue.  Is the problem that the "Everything reset" portion of the alert is confusing since the "Reset All" only applies to the open screen?

**Comment by carenwatkins** [comment]
@jessegreenberg yes, the meaning between "restart skater" and "everything restarted", on Energy Skate Park for example, may conflate for the user. Even though there is the follow-up sentence "Everything Reset" it may be too late in the cognitive processing cycle to be clarifying for the user.

**Comment by jessegreenberg** [comment]
I see, thanks @carenwatkins, I thought you meant this was an issue for multiple screens. Could you please clarify what you mean by "cognitive processing cycle"?  When "Reset All" is pressed, everything in the open screen is restarted so the alert seems accurate to me.  If "Restart Skater" has its own alert (like "Skater moved to initial drop location") is this still an issue?

**Comment by emily-phet** [comment]
@carenwatkins The Balloons and Static Electricity sim also has two reset buttons - the "Reset All" button and "Reset Balloon(s)" button. 

Also, it might be useful to note that the "Reset All" button has a long history with PhET (the original PhET sims had a button labeled as "Reset" or "Reset All"). The phrase "Reset All" is also how we describe this button in all of our supporting materials. Any wording tweaks will need to be with the descriptions, rather than the button label itself.

**Comment by carenwatkins** [comment]
Of course, @jessegreenberg. I should say "cognitive processing", and what I mean is processing can be a spectrum of differences--including processing speed. 

I think "Skater moved to initial drop location" could work. Will revisit it in context of the sim. thanks!

**Comment by jessegreenberg** [comment]
Ok, thanks @carenwatkins! Closing this issue then.
