### ISSUE TITLE
Investigate grid interactions in preparation for 3/21 Keyboard Access Meeting

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#23]
@jessegreenberg @terracoda Not sure if this is being tracked elsewhere. If not, can you all put any links to examples you have here, for discussion?

**Comment by terracoda** [comment]
Thanks @emily-phet for posting this issue. I've started a google doc in the Keyboard Navigation folder [Complex Controls and Interactions](https://docs.google.com/document/d/1gUeYfAPN1RdcePvGqslfhEM62Ru6U6UgunWv6AYnLsI/edit#), and will be adding considerations and resources there.

**Comment by jessegreenberg** [comment]
Here is the example from the IDRC for grid navigation:
http://build.fluidproject.org/infusion/demos/reorderer/gridReorderer/

**Comment by terracoda** [comment]
@emily-phet and @jessegreenberg, my notes on the grid interaction are still pretty rough.
I added draft labels for some of the tools in the Area Builder design document and then decided to start a draft PDOM for Area Builder to help me think through the interaction with the grid a bit more.

I am wondering if it is technically possible to have two grids, on e for the board and one for the bucket of tiles. Or structurally make the bucket of tiles as part of the grid. Working on those thoughts.

**Comment by emily-phet** [comment]
@terracoda I took a look at your notes in the doc. If you could add a little more clarification around the two grid idea, that would be helpful. It's not clear to me (though I think I'm just misunderstanding something) why we would want a grid for the tiles *in the bucket*. 

I made some notes towards the end of the document (with a new heading) that lists out what I think are the pros and cons for the two possible one grid approaches. Didn't try this with the two grid approach because I'm not sure I'm understanding that one. I think moving the tiles on the grid (the one grid option where you *do not* choose grid location in a hover state) is a no go since we need to know where the user wants to put a tile and then have the option to move it somewhere else for the user. This doesn't seem possible to me without having an intermediate mode where the user is selecting the location for the tile in a hover state.

**Comment by terracoda** [comment]
@emily-phet working on clarifications.

**Comment by terracoda** [comment]
@emily-phet, I created a 5th example (a little more thought out). I will try to adjust the the cognitive walk-through or create a new one before tonight's meeting.

**Comment by jessegreenberg** [comment]
@terracoda @emily-phet can this issue be closed now?
