### ISSUE TITLE
Teacher Survey - Review

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#28]
@ariel-phet @kathy-phet 
As part of the collaboration with Georgia Tech, we will be sending a survey out to the teachers regarding their use of PhET sims, and potential barriers or challenges they have with regard to sim use. 

We would like to finalize this survey by April 18th, send out to a small number of people, refine, and send out to the PhET email list of teachers (and social media, etc.) on April 24th. 

The idea is to send out a more general [initial survey](https://docs.google.com/spreadsheets/d/1P8PbKjSweGmfj6QFGG4A5KQ3DUVG4Qpbr7TAZqiX53U/edit?usp=sharing), and collect emails of those who would be specifically interested in follow-up surveys. Later we will ask more specific questions about technical access and use by students with disabilities to those who "opt in" to getting a follow-up survey.

Please take a look at our latest draft, and edit/comment as you see fit. If you could give your feedback by Friday, April 14th, that would be ideal.

**Comment by kathy-phet** [comment]
Emily - Re timing, can we do these emails after our fundraising campaign? Fundraiser runs from April 20-April 30.

**Comment by emily-phet** [comment]
@kathy-phet That will probably work. We are trying to make sure we don't hit the end of the school year for US or international teachers, but probably starting a few days into May will be fine. We plan to have the survey open for 3 weeks (with Qualtrix reminders for any unfinished surveys during that time) to allow for international teachers who may be on break to get a chance to complete it.

**Comment by kathy-phet** [comment]
Thanks. Sounds good. Also, we will be doing a Math Teacher survey -- so we are actually excluding those math teachers from the fundraising campaign emails (there just aren't that many of them at this point). If you want to do your pilot survey earlier, we can work to set aside a sample of teachers for that as well. In general, you will need to identify what the filters will be (K12, science only, etc.)?

**Comment by emily-phet** [comment]
@kathy-phet We're hoping to include as the survey population all of the teacher users we can find (from email and social media sharing) for this initial, more general survey. Then narrow to specific sub-populations in future work. Is there a specific reason you can think of to narrow the population we send the survey to in advance? The goals we've discussed with the GT folks are to:
- Get an overall sense of the prevalence of big picture challenges, and to
- Provide teachers an opportunity to "opt in" to more detailed follow-ups (so we can ask specific questions related to subpopulations of teachers and those who have experienced specific barriers or challenges)

**Comment by kathy-phet** [comment]
I'm just saying for your initial survey testing prior to the big send, the " send out to a small number of people," part.

**Comment by emily-phet** [comment]
@kathy-phet Ahh, I see. Thanks for the clarification.

**Comment by emily-phet** [comment]
Notes from Discussion with Prakriti and Carrie:
- feedback from international teachers and screen reader users (possibly trusted translators for international perspective)
- Need to consider accessibility of questions, and how the wording maps to access of responses.
- A/B testing of options for a few of the more troublesome questions
- Aiming for pilot testing between now and April 30th, then sending out full survey first week of May.

**Comment by emily-phet** [comment]
@kathy-phet @ariel-phet Just a reminder that we'll need your feedback on the survey today. The next step will be finalizing a few of the questions that are still in flux, putting in Qualtrix format, and testing informally with a few teachers. Then we'll send out to a subgroup of teachers (~1,000 teachers), do any refining, and then send out to everyone first week of May.

**Comment by ariel-phet** [comment]
Row 24: not sure about the phrase "non-traditional students"

Row 30: Would someone continue to use us if their teaching was Less effective? 

Row 47: Lack of the appropriate device is probably an issue (device that won't run java or needs java update). Also I think you might distinguish between lack of internet and poor internet

Otherwise looks pretty clear

**Comment by emily-phet** [comment]
@kainip Can you please update Row 47 to address @ariel-phet comment above?

**Comment by kainip** [comment]
@emily-phet looks like Row 47 is already updated?

**Comment by ariel-phet** [comment]
@emily-phet looks like this issue can be closed since the survey was published and advertised?

**Comment by emily-phet** [comment]
Survey was sent out!
