### ISSUE TITLE
CSUN 2016 Manuscript

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#4]
@taliesin - I'm just wrapping up a book chapter this week. Please let me know when you'll be progressing the manuscript for CSUN, so we can coordinate. Looks like it's T-20 days to the due date!
Note - please send any outline/draft/specific details by email. I just wanted to open an issue about this for progress tracking.

**Comment by terracoda** [comment]
@emily-phet, just got added to this repo :-) I've been thinking about. I will gather the all the resources (abstract, review, images, and other related resources). I should aim for draft rather than an outline by Friday Nov 18th.

**Comment by emily-phet** [comment]
@terracoda - great! Let's make sure there is an outline to start, though. Can you try to have an outline for us to discuss by the 16th? I know you're prepping for a conferene, so the outline doesn't need to be super detailed. I'll email you an example of the outline I used for the book chapter I'm wrapping up as a recent example.

**Comment by terracoda** [comment]
@emily-phet Yes, I will make an outline with word counts and work in ideas that were suggested by the reviewers. Will aim for mid-week on this. The presentation I am preparing should also help with outlining.

**Comment by terracoda** [comment]
@emily-phet, thanks for your great feedback on the outline. I've started to flesh out the Results & Discussion section. I've uploaded my work to the shared folder, but no need to review it yet.

**Comment by terracoda** [comment]
@emily-phet, I only got a few tweaks to the manuscript today. I'll make sure I get a good chunk of time on it tomorrow after my morning interview.

**Comment by emily-phet** [comment]
Submitted! @terracoda to put submitted docs in Google drive for reference.

**Comment by terracoda** [comment]
I put the files in PhET Files/Accessibility/Publications
