### ISSUE TITLE
labels for browser/AT bug reports

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/a11y-research#42]
From meeting on 6/9/17, this repository will collect bug reports to be sent to browsers/AT.  For organization, labels would be helpful to see issues related to this.

We already have labels:
```dev:a11y```
```dev:sonification```
```design:a11y```
```type:bug```

scenery repository has labels
```scenery:to-submit-browser-bug```
```scenery:browser-bug```

For third party a11y bugs, what about something like
```a11y-research:platform-bug```

```platform-bug``` term includes both screen reader and browser.  And having only one label for all bugs makes searching easier since that label can be searched or clicked on to see the list of all platform bugs.

Thoughts @emily-phet @terracoda @zepumph?

**Comment by zepumph** [comment]
It seems like we have a lot of a11y like labels that are scattered in different label types, could this be a good time to solidify a set of a11y specific labels. Perhaps we don't have much else that needs a label.

I may prefer "a11y:platform-bug", but don't feel too strongly.

**Comment by jessegreenberg** [comment]
> It seems like we have a lot of a11y like labels that are scattered in different label types,

Hmm, could you provide an example?  It looks like PhET github labels have been categorized into ```dev:*```, ```meeting:*```, ```design:*```, ```status:*```, and so on.

> I may prefer "a11y:platform-bug", but don't feel too strongly.

I like ```a11y:platform-bug```.

**Comment by jessegreenberg** [comment]
Ah, @zepumph maybe you were suggesting we merge dev:a11y and design:a11y?  I'd be fine with that.

**Comment by zepumph** [comment]
After thinking about it. I like it the way it is now. To help process this I thought about phet-io labels. There is dev:phet-io, meeting:phet-io, but also a whole phet-io: category for phet-io specific labels. So far no a11y labels have really warranted their own category, but I'm sure there will be more in the future, which is why 'a11y:' is a nice category to add SO MANY LABELS to in the future. right now just platform-bug, but oh the possibilities are endless.

**Comment by jessegreenberg** [comment]
Ok, thanks @zepumph, that sounds great.  Haven't heard from others yet, but I think we can proceed with ```a11y:platform-bug```.

**Comment by jessegreenberg** [comment]
I created it and will apply to related issues, closing.

**Comment by terracoda** [comment]
Oops forgot about this issue. I agree that an ally: would be good to have as a category. And I like `a11y:platform-bug` that combines bugs.

Does this mean labels will be more like this?
a11y:dev
a11y:sonification
a11y:design
a11y:platform-bug

**Comment by zepumph** [comment]
We decided against this approach. There is a11y:platform-bug, but all the other ones are as they were before.

**Comment by terracoda** [comment]
@zepumph, thanks for the clarification.
