### ISSUE TITLE
What license should this repo have?

### ISSUE THREAD

**Issue by samreid** [phetsims/a11y-research#46]
Discovered in https://github.com/phetsims/tasks/issues/875, this repo should probably have a license.  I'm not too familiar with it, so not sure what's appropriate.

**Comment by jessegreenberg** [comment]
Good question, I would say MIT?  This repo organizes general accessibility questions and issues.  Code in this repo will either be raw HTML design trials or mockups for the parallel DOM, or tests to understand ARIA behavior and support. This repo is very much "not a sim", so MIT seems best.

**Comment by jessegreenberg** [comment]
https://github.com/phetsims/a11y-research/issues/46#issuecomment-317500763 This overview is not obvious from the README Ill update it.

**Comment by samreid** [comment]
Based on your explanation MIT sounds good, thanks!

**Comment by jessegreenberg** [comment]
Great, thanks @samreid!  Added the MIT license, closing.
