### ISSUE TITLE
Link to keyboard shortcuts in scene summary

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/a11y-research#49]
In the scene summary for a few sims I have seen a bullet that looks like

```html
If you need to, check out the <a>keyboard shortcuts</a> for this sim.
```

The keyboard help dialog is typically opened with a button that just toggles its visibility.  Is this shortcut necessary?  If so can it be a button?  If a link, is it OK if there is no destination?

**Comment by terracoda** [comment]
@jessegreenberg, I have some notes on this.

The idea for the link to a button rather than a direct button was to make it a little less desirable on initial startup. We don't want it to get in the way. However, for people who really need it, they are told right away where it is.

My earlier research convinced me that it was legal to link to a button on  page, though it is not super common.

@jessegreenberg , what do you mean by no destination? Is the navbar not there on screen load?

**Comment by jessegreenberg** [comment]
I see, thanks.

> My earlier research convinced me that it was legal to link to a button on page, though it is not super common.

Interesting, I didn't realize that.  I am not too sure yet how that would work.

> what do you mean by no destination?

I meant that I don't know what the href would be, I don't know what the link would point to.

**Comment by jessegreenberg** [comment]
Is the link going to open the dialog or send focus to the button in the navigation bar?

**Comment by terracoda** [comment]
@jessegreenberg, the idea was to link to the button, not open the dialog. If we take this approach,
the href for the anchor would be the id of the button.

**Comment by jessegreenberg** [comment]
I see thanks! It looks like if we prefix the id with a '#', it should work.

**Comment by jessegreenberg** [comment]
Hmm, but that updates the url, is that reloading the page?

**Comment by terracoda** [comment]
@jessegreenberg, good catch. 
Yes, internal page links are added to the url. I don't know about page refreshing, but that url would take focus to the button and not the top of the sim if someone were to copy and paste the link into another browser tab.

**Comment by jessegreenberg** [comment]
Scenery might not support this out of the box.  Since scenery doesn't use DOM id's anymore we will need to add a way to get the id for the href.  We will also need to make sure that we can add this in a secure way.  Including a link in a translatable description might introduce cross site scripting vulnerabilities.

**Comment by jessegreenberg** [comment]
> Hmm, but that updates the url, is that reloading the page?

Some google searching says it will not reload the page.

> but that url would take focus to the button and not the top of the sim if someone were to copy and paste the link into another browser tab.

I am not sure if that is a problem, what do you think @terracoda?

**Comment by terracoda** [comment]
@jessegreenberg, as long as the url works, I don't think it is a problem.

**Comment by mbarlow12** [comment]
Not sure if this is supported, but if we're trying to simply move focus to the dialog button, we could also utilize data attributes. That might offer a cleaner/more secure way to interact with Scenery.

**Comment by jessegreenberg** [comment]
@mbarlow12 and I discussed potentially adding data attributes as a way to manage focus.  We also talked about using a click listener instead of ```href``` as a way to send focus to the button, and this would likely integrate with Scenery more directly, and also wouldn't modify the URL at all.

**Comment by jessegreenberg** [comment]
@terracoda are you OK with the link not being in the focus order?

**Comment by jessegreenberg** [comment]
Click event works great, thanks @mbarlow12.

So now we need to solve two more issues:

- The string with the link needs to be translatable, and the formatting needs to work for RTL languages.
- We need access to the keyboard help button from anywhere in the sim, particularly where we create the scene summary content.

**Comment by jessegreenberg** [comment]
Since there is only one KeyboardHelpButton in a sim, we can use a singleton pattern and get the instance statically from anywhere.

> The string for the link needs to be translatable, and the formatting needs to work for RTL languages.

It seems that PhET does not support embedding links in text, this doesn't work for internationalization.  Here is what I have been thinking:
- Cannot use joist.LinkText - Would require chunks of Text and LinkText, not suitable for i18n.
- Cannot use joist.RichText - Translator would be able to translate the link, big security risk.

@terracoda a couple of potential solutions are:
- The whole sentence is a link
```<a>If needed, check out the keyboard help dialog for this sim</a>```
- We break the sentence and the link explicitly, which is much more friendly for i18n.
 ```<p>If needed, check out the keyboard help dialog for this sim.<p>```
```<a>Keyboard Help Button</a>```
- Another option?

I prefer the first option.

**Comment by terracoda** [comment]
@jessegreenberg, 

- Re https://github.com/phetsims/a11y-research/issues/49#issuecomment-320354053 on not including the link in the Tab Order. Yes, in fact, it is preferable that it not be in the Tab Order.
- Re https://github.com/phetsims/a11y-research/issues/49#issuecomment-320334449 on data-attributes, I think this is an interesting approach. I don't know exactly what data-attributes are, however, or how accessible they can be made. If we have control over the accessibility, I think this approach is a good one.
- Re https://github.com/phetsims/a11y-research/issues/49#issuecomment-320378315, I also prefer option 1. The amount of text for the link is long, but we could shorten it, if need be.

**Comment by jessegreenberg** [comment]
All sounds good @terracoda, thanks.  Reassigning to me to implement.

**Comment by jessegreenberg** [comment]
It sounds like RichText will now support adding arbitrary callbacks to the links, which means that we should be able to support the original scene summary item with an embedded link in a way that is safe and i18n friendly!
```html
If needed, check out the <a>keyboard help</a> for more information
```
(thats might not be the exact working)

**Comment by terracoda** [comment]
@jessegreenberg, I had 

> If you need to, check out the `<a href="#keyboard-shortcuts">keyboard shortcuts</a>` for this sim.

However,
>> If needed, check out the `<a href="#keyboard-shortcuts">keyboard shortcuts</a>` for this sim.

is shorter.

**Comment by terracoda** [comment]
As discussed in the Ohm's Law repo https://github.com/phetsims/ohms-law/issues/99, we are putting this idea on hold, as the link be the first item in the tab order for all sims...likely not what we want.

Providing the hint that help for keyboard use exists is likely just enough:
- "If you need to, check out the Keyboard Shortcuts for this sim." , or the slightly shorter phrase
- "If needed, check out the Keyboard Shortcuts for this sim."

We are trying these phrases in BASE and OL.

**Comment by terracoda** [comment]
Closing this issue.
