### ISSUE TITLE
Interesting styling tool for input type range

### ISSUE THREAD

**Issue by terracoda** [phetsims/a11y-research#68]
I just wanted to share this styling tool with @jessegreenberg , @zepumph and @mbarlow12 in case it is at all helpful.

[http://danielstern.ca/range.css/#/](http://danielstern.ca/range.css/#/)

**Comment by zepumph** [comment]
That's really cool thanks! Very flexible.

**Comment by jessegreenberg** [comment]
This looks really nice, thanks @terracoda!

**Comment by zepumph** [comment]
That is awesome thanks. I'm going to close this issue.
