### ISSUE TITLE
Onboarding Georgia Tech team to description work for MAL and GFL:B

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#74]
- [ ] Play with each sim, make list of questions regarding learning goals, visual design choices, and interactions

- [ ] Meet with Ariel to discuss these questions. From this meeting, create prioritized list of the top three relationships to emphasize. This will help you later when making decisions re descriptions.

- [ ] For each sim, make a spreadsheet that has the structure of the Ohm's Law description spreadsheet. Begin filling this in with draft descriptions.

**Comment by terracoda** [comment]
@kainip, here's the issue.

**Comment by emily-phet** [comment]
@kainip Can you replace the default image with some kind of avatar in Github? The team likes to have that to help disambiguate folks quickly.
