### ISSUE TITLE
Two Figures needed for Manuscript by Tuesday

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#75]
Need someone to make two figures for a paper I'm working on about Scenery and the Parallel DOM. The figures are simple tree diagrams, but I'd like them to look really polished. Here's a starting sketch.
![scenery-diagram](https://user-images.githubusercontent.com/5109055/34880082-849c33c2-f76c-11e7-8168-5d709dc79a7a.png)

- [ ] First Figure: Has the label at the top "Scene Graph", then the same tree structure as in the starting sketch. The whole tree structure (but not the text "Scene Graph") needs to be inside of a box. Then there is one arrow (centered) pointing straight down from the tree structure box. That arrow points to one yellow balloon and one green balloon (from BASE) each with charges as shown in starting sketch. These balloon are from BASE, but not from a screenshot like in the sketch. Can the original images be grabbed from somewhere? Or are they drawn...? 

- [ ] Second Figure: Has the label at the top "Scene Graph", then the same tree structure as in the starting sketch. The whole tree structure (but not the text "Scene Graph") needs to be inside of a box. Then there is *two* arrows (one pointing off the left and one off to the right - as in the starting sketch). The left arrow points to the same balloons as in the First Figure. The right balloon points to text as in the starting sketch.  

Ta da - the addition of the PDOM illustrated in two figures. Scenery makes a visual representation and an (accessible) non-visual representation - changing the world of accessible complex interactives forever. :)

**Comment by ariel-phet** [comment]
@emily-phet I will check with Dave Underwood to see if he is available, but you might be on your own on this one. Monday is a University holiday, and I am not sure of anyone else that can do this on such short notice. 

I will update the issue if Dave is available.

**Comment by ariel-phet** [comment]
Looks like Dave is available. I have emailed him the issue.

**Comment by emily-phet** [comment]
All done.
