### ISSUE TITLE
find ASSETS papers related to methodology

### ISSUE THREAD

**Issue by briannatomlinson** [phetsims/a11y-research#78]
@emily-phet would like me to see if there are any other method-heavy papers from ASSETS that have done similar work to what we're planning. 

I'll put any particular updates here if there are relevant ones, or summarize otherwise

**Comment by briannatomlinson** [comment]
I started doing it this afternoon, and have gone through all of the ASSETS 2017 papers to find relevant ones. I'm making an excel sheet for this & will probably look through 2015 & 2016 then post something else on it

**Comment by emily-phet** [comment]
@briannatomlinson Great! We just need one or two nice examples, though. Once you've found that, you can stop looking.

**Comment by briannatomlinson** [comment]
Did you want me to share the papers here? (like links/docs) or are you more interested to know the kinds of activities they did & how. I wasn't sure what level of detail you were looking for. @emily-phet

**Comment by briannatomlinson** [comment]
For example, I made a quick chart as I was going through them to see which would be best. I found a few that match way better with what we're thinking of doing but I was trying to get a better idea about what the typical trends were. So I can just upload the full sheet, or give you just a couple of the super-relevant ones.

![image](https://user-images.githubusercontent.com/27776200/35414893-dc425144-01f1-11e8-8344-8f8b97d685da.png)

**Comment by emily-phet** [comment]
@briannatomlinson If you feel you have a general sense of the community from skimming, we can use that to inform our final study design. For me, just passing a long a few of the most relevant papers will be fine.

**Comment by briannatomlinson** [comment]
Emily, here are three papers that I think are pretty good examples. Most of them seemed to use semi-structures interviews, think alouds, or contextual inquiries, and a few used other pieces like the SUS, speed, accuracy, and likert questions.

[p171-szpiro.pdf](https://github.com/phetsims/a11y-research/files/1677908/p171-szpiro.pdf)
[p200-shi.pdf](https://github.com/phetsims/a11y-research/files/1677949/p200-shi.pdf)
[Zolyomi, Shukla, Snyder - Technology - Mediated Sight A Case Study of Early Adopters of a Low Vision Assistive Technology.pdf](https://github.com/phetsims/a11y-research/files/1677953/Zolyomi.Shukla.Snyder.-.Technology.-.Mediated.Sight.A.Case.Study.of.Early.Adopters.of.a.Low.Vision.Assistive.Technology.pdf)

**Comment by briannatomlinson** [comment]
And here's the full set of stuff from the chart I made last week
![assets examples](https://user-images.githubusercontent.com/27776200/35570395-1e4e7474-059d-11e8-8449-3edbe053fcef.PNG)
