### ISSUE TITLE
Get stuff together to handle paying participants

### ISSUE THREAD

**Issue by briannatomlinson** [phetsims/a11y-research#79]
Check with bruce today about how we pay participants (outside of people recruited through CVI, excel, GLASS staff, etc.)

**Comment by briannatomlinson** [comment]
I talked with one of our finance admins to get the paperwork that needs to be turned in. I've sent Bruce a message about it & shoved it under his door since I'm working from home tomorrow. 

I've also had the IRB returned so I can update the language for everything & re-submit tomorrow

**Comment by briannatomlinson** [comment]
@emily-phet I got a response from Bruce for this! He filled out the document I have to submit, I made the changes to the IRB docs (the protocol info+consent forms) and have submitted it to him to forward to the IRB. 

I'm not sure how long it will take for me to hear from them, but I can check in next week?

**Comment by emily-phet** [comment]
Great, thanks!

**Comment by briannatomlinson** [comment]
@emily-phet  I'm just waiting on the letter from Pat Herndon at GLASS. Everything else should be good to go for recruiting through them. I've fixed all of the IRB stuff and can resumbit today once I get it. 

I called her earlier and she said she'd get it to me ASAP! :D

**Comment by briannatomlinson** [comment]
Also once this IRB is updated we can pay adult recruited participants from CVI, too. I sent Stephanie a recruitment email this morning about that.

**Comment by briannatomlinson** [comment]
Got the letter yesterday & submitted this IRB early afternoon. Should be good to go soon, but I can try to follow up with the IRB if I don't hear anything back in the next couple of days.
