### ISSUE TITLE
Need latest links to share with MIT folks for conference 1/29

### ISSUE THREAD

**Issue by emily-phet** [phetsims/a11y-research#81]
Need latest and greatest links (a11y and a11y-view) for:

Auditory description and keyboard nav:
- Ohm's Law
- Resistance in a Wire
- BASE

Keyboard Navigation:
- Rutherford Scattering
- Plinko Probability
- Maybe Coulomb's Law (to show off the cool ruler!)

**Comment by terracoda** [comment]
These are the latest public **dev prototypes** I can find:

**Auditory description and keyboard nav:**
- Ohm's Law
  - https://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.17/ohms-law_en.html?accessibility
  - OL A11y View
    - https://www.colorado.edu/physics/phet/dev/html/ohms-law/1.4.0-dev.17/ohms-law-a11y-view.html

- Resistance in a Wire (**Labels Only - no dynamic content yet**)
  - https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.4.0/resistance-in-a-wire_en.html?accessibility
  - RIAW A11y View
    -  https://www.colorado.edu/physics/phet/dev/html/resistance-in-a-wire/1.4.0/resistance-in-a-wire-a11y-view.html

- Balloons and Static Electricity
  - https://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.9/balloons-and-static-electricity_en.html?accessibility
  - BASE A11y View
    - https://www.colorado.edu/physics/phet/dev/html/balloons-and-static-electricity/1.4.0-dev.9/balloons-and-static-electricity-a11y-view.html

**Keyboard Navigation**
- Rutherford Scattering:
  - https://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.1.0-dev.2/rutherford-scattering_en.html?accessibility
  - RS Ally View:
    - https://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.1.0-dev.2/rutherford-scattering-a11y-view.html

- Plinko Probability
  - https://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.2.0-dev.2/phet/plinko-probability_en_phet.html?accessibility
  - PP A11y View:
    - https://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.2.0-dev.2/phet/plinko-probability_a11y_view.html

- Gravity Force Lab: Basics
  - https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-test-keys.1/gravity-force-lab-basics-a11y-view.html
  - GFLB A11y View
    - https://www.colorado.edu/physics/phet/dev/html/gravity-force-lab-basics/1.0.0-test-keys.1/gravity-force-lab-basics_en.html?accessibility

- Coulomb's Law (**Ruler not fixed yet in this version**)
  - https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.8/coulombs-law_en.html?accessibility
  - CL A11y View:
    - https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.8/coulombs-law-a11y-view.html

**Comment by terracoda** [comment]
@jessegreenberg, if you know of any later dev versions  of RIAW or Coulomb's Law, please publish links.

**Comment by terracoda** [comment]
Oh, I see we have until Jan 30 for this.

**Comment by jessegreenberg** [comment]
@emily-phet @terracoda [this bug](https://github.com/phetsims/chipper/issues/648) will impact a11y views  for Rutherford Scattering, Plinko Probability, and Coulomb's Law.

@mbarlow12 found that the a11y view for milti-screen sims are borken in FF and Safari because invisible screens remain in the focus order. Does this bug need to be fixed before 1/30 or can we assume people will show with Chrome?

**Comment by terracoda** [comment]
Since these are prototypes with known issues, I personally think it is fine to place caveats on how to view the links.

@emily-phet, do you have any concerns?

**Comment by emily-phet** [comment]
@jessegreenberg @terracoda 
In general, I agree with @terracoda that prototypes can come with caveats. This bug does need to be fixed in the long-term - as we use and publish links to more of these there will be more folks over time aware and trying to make use of them. 

@jessegreenberg do you any idea of how difficult this might be to fix? If it's relatively quick, I think it would be best to get it done before Monday. If not, we can hold off until later.

**Comment by emily-phet** [comment]
@terracoda @jessegreenberg Just to clarify, the event is 1/29 (the title of this issue is a typo), but I need at least some links to send along today. Kyle and Mary (and others that will be running the booth) want to practice using the sims in advance.

**Comment by terracoda** [comment]
@emily-phet, are the links above ok? The links to OL and BASE will likely not change before the 29th.

**Comment by jessegreenberg** [comment]
> do you any idea of how difficult this might be to fix?

It is unclear, I will look into this now to get a better sense.

**Comment by jessegreenberg** [comment]
This bug has been fixed. @emily-phet would you like new links with this fix or have we missed our window?

**Comment by jessegreenberg** [comment]
- Rutherford Scattering:
  - Sim: https://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.1.0-dev.3/phet/rutherford-scattering_en_phet.html?accessibility
  - a11y view: https://www.colorado.edu/physics/phet/dev/html/rutherford-scattering/1.1.0-dev.3/phet/rutherford-scattering_a11y_view.html
- Plinko Probability:
  - Sim: https://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.2.0-dev.3/phet/plinko-probability_en_phet.html?accessibility
  - a11y view: https://www.colorado.edu/physics/phet/dev/html/plinko-probability/1.2.0-dev.3/phet/plinko-probability_a11y_view.html
- Coulombs Law:
  - sim: https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.11/phet/coulombs-law_en_phet.html?accessibility
  - a11y view: https://www.colorado.edu/physics/phet/dev/html/coulombs-law/1.0.0-dev.11/phet/coulombs-law_a11y_view.html

Links @terracoda gave for the single screen sims are still latest and weren't affected by this bug. Removing my assignment but let me know if anything else is needed.

**Comment by terracoda** [comment]
I am also removing my assignment. @emily-phet let us know if you need anything else. There are links to:
