### ISSUE TITLE
add Prakriti to a11y-research

### ISSUE THREAD

**Issue by briannatomlinson** [phetsims/a11y-research#89]
Can we add Prakriti to this repo? I don't know that I have permission for it. 

Since she's going to be doing work in Kenya/with inABLE, she & I will be coordinating closely and would be good to keep her in the loop on this.

**Comment by terracoda** [comment]
@briannatomlinson, does Prakriti have a github handle? I am pretty sure the repo is public. Prakriti should be able to comment on anything.

There is very little code in this repository, but I am pretty sure anyone can pull the repo.

Does Prakriti need to push stuff to the repo?

**Comment by briannatomlinson** [comment]
Oh, ok! I just didn't know if she should join this too, since she was working on evaluation stuff. I was just hoping to keep her in the loop better, or make it easier for her to track/keep Emily aware of what was going on.

I'll have her check and see! Thanks @terracoda!

**Comment by pkaini** [comment]
Thanks @terracoda @briannatomlinson! I was able to join
